const $=id=>document.getElementById(id);let selectedFile=null,mediaRecorder=null,chunks=[];
const fileInput=$('audioFile'),drop=$('drop'),preview=$('preview'),analyzeBtn=$('analyzeBtn'),recordBtn=$('recordBtn');
function bytes(n){if(!n)return'0 B';const u=['B','KB','MB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),2);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
function setFile(file){if(!file||!file.type.startsWith('audio/')){selectedFile=null;analyzeBtn.disabled=true;$('fileTitle').textContent='Please select an audio file';$('fileMeta').textContent='Supported: WAV, MP3, M4A, FLAC, OGG, WEBM';return}selectedFile=file;$('fileTitle').textContent=file.name;$('fileMeta').textContent=`${bytes(file.size)} · ${file.type||'audio'}`;preview.src=URL.createObjectURL(file);preview.style.display='block';analyzeBtn.disabled=false}
fileInput.onchange=e=>setFile(e.target.files[0]);['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('active')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('active')}));drop.ondrop=e=>setFile(e.dataTransfer.files[0]);
recordBtn.onclick=async()=>{if(mediaRecorder&&mediaRecorder.state==='recording'){mediaRecorder.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:mediaRecorder.mimeType||'audio/webm'});setFile(new File([blob],'live-voice-sample.webm',{type:blob.type}));$('recordStatus').textContent='Recording captured — ready to analyze';recordBtn.textContent='● START RECORDING'};mediaRecorder.start();$('recordStatus').textContent='Recording… click stop when finished';recordBtn.textContent='■ STOP RECORDING'}catch(e){alert('Microphone access was not available. You can upload an audio file instead.')}};
function showResult(d){const p=Math.round((d.ai_probability||0)*100),c=Math.round((d.ai_confidence||0)*100),lvl=(d.risk_level||'').toLowerCase();$('prob').textContent=`${p}%`;$('confidence').textContent=`${c}%`;$('risk2').textContent=d.risk_level||'--';$('recommendation').textContent=d.recommendation||'--';$('reason').textContent=d.risk_reason||'';$('risk').textContent=d.risk_level||'UNKNOWN';$('risk').dataset.level=lvl;$('bar').style.width=`${p}%`;const v=$('verifyBtn');v.classList.toggle('hidden',lvl==='low');$('result').classList.remove('hidden');$('result').scrollIntoView({behavior:'smooth',block:'start'})}
analyzeBtn.onclick=async()=>{if(!selectedFile)return;const f=new FormData();f.append('audio_file',selectedFile);analyzeBtn.disabled=true;$('loading').classList.add('show');$('result').classList.add('hidden');try{const r=await fetch('/api/analyze',{method:'POST',body:f}),d=await r.json();if(!r.ok)throw Error(d.detail||'Analysis failed');showResult(d);loadHistory()}catch(e){alert(e.message)}finally{$('loading').classList.remove('show');analyzeBtn.disabled=!selectedFile}};
$('verifyBtn').onclick=async()=>{const r=await fetch('/api/verification',{method:'POST'}),d=await r.json();$('verifyMsg').textContent=`✓ ${d.message}`};
async function loadHistory(){try{const r=await fetch('/api/results?limit=10'),rows=await r.json();$('historyList').innerHTML=rows.length?rows.map(x=>`<div class="historyItem"><span class="name">#${x.id} · ${x.filename}</span><b data-level="${(x.risk_level||'').toLowerCase()}">${x.risk_level} · ${Math.round((x.ai_probability||0)*100)}%</b></div>`).join(''):'<span class="muted">No analyses yet.</span>'}catch(e){$('historyList').innerHTML='<span class="muted">History unavailable.</span>'}}
$('refreshBtn').onclick=loadHistory;loadHistory();
